"""make cron default and add cron_expression

Revision ID: 261665a615ae
Revises: 1fee55191412
Create Date: 2025-12-30 21:18:12.043831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261665a615ae'
down_revision: Union[str, Sequence[str], None] = '1fee55191412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False, foreign_key='jobs.id'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobrunstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, foreign_key='users.id'),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=False),
    sa.Column('schedule_type', sa.Enum('CRON', 'EVENT', name='schedule_type_enum'), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', 'PAUSED', name='job_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
