"""make cron default and add cron_expression

Revision ID: dc676e6b90a1
Revises: 261665a615ae
Create Date: 2025-12-30 21:21:07.317251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc676e6b90a1'
down_revision: Union[str, Sequence[str], None] = '261665a615ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'job_runs', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'job_runs', type_='foreignkey')
    # ### end Alembic commands ###
